version: "3.9"
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/certs:/etc/nginx/certs
      - ../nginx/log:/var/log/nginx
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companior
    depends_on:
      - nginx-proxy
    volumes:
      - ../nginx/certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  user-frontend:
    environment:
      - VIRTUAL_HOST=reactjs.${HOST}
      - LETSENCRYPT_HOST=reactjs.${HOST}
    expose:
      - 3000

  express:
    environment:
      - VIRTUAL_HOST=nginx.${HOST}
      - LETSENCRYPT_HOST=nginx.${HOST}
    expose:
      - 4001

volumes:
  conf:
  vhost:
  html:
